# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: quefep
custom: # Replace with a single custom sponsorship URL, email, or link to a dedicated funding page

# If you need to use a custom URL, uncomment and customize the following line:
# custom: https://github.com/sponsars/yourusername
